openapi: 3.1.0
info:
  title: TwinSpect
  description: Datamodel for the universal near-duplicate benchmark
  version: 0.1.0
components:
  schemas:
    Dataset:
      title: Dataset
      type: object
      description: A dataset used for near-duplicate benchmarking
      required:
      - name
      - url
      - mode
      properties:
        name:
          type: string
          description: The name of the dataset
        label:
          type: string
          description: Short label used in tables and as folder name
        url:
          type: string
          format: uri
          description: Download url for dataset
        mode:
          type: string
          description: Perceptual mode of media assets
          enum:
          - text
          - image
          - audio
          - video
        installer:
          type: string
          description: Full path to python function that installs the dataset
        samples:
          type: integer
          description: Number of samples to install from the dataset
        clusters:
          type: integer
          description: Number of similarity clusters to build for dataset
    Transformation:
      title: Transformation
      type: object
      description: A transformation being applied to a media asset
      required:
      - name
      - mode
      - function
      properties:
        name:
          type: string
          description: The name of the transformation
        mode:
          type: string
          description: Perceptual mode of media assets
          enum:
          - text
          - image
          - audio
          - video
        function:
          type: string
          description: Full path to python function that applies the transformation
        params:
          type: array
          description: A list of transformation parameters to be used with the function
    Configuration:
      title: Configuration
      type: object
      description: Benchmark configuration
      required:
      - twinspect
      - datasets
      - transformations
      properties:
        twinspect:
          type: string
          description: Configuration file format version
        datasets:
          type: array
          items:
            $ref: '#/components/schemas/Dataset'
          description: List of Datasets
        transformations:
          type: array
          items:
            $ref: '#/components/schemas/Transformation'
          description: List of Transformations
