openapi: 3.1.0
info:
  title: TwinSpect
  description: Datamodel for the universal near-duplicate benchmark
  version: 0.1.0
components:
  schemas:
    Algorithm:
      title: Algorithm
      type: object
      description: An algorithm for similarity preserving compact codes
      required:
      - name
      - label
      - mode
      - function
      properties:
        name:
          type: string
          description: The name of the Algorithms
        label:
          type: string
          description: Short labes used in tables and for file names
        mode:
          type: string
          description: Perceptual mode of algorithm
          enum:
          - text
          - image
          - audio
          - video
        function:
          type: string
          description: Full path to python function that implements the algorithm. The function must accept
            a file path as the first parameter and must return a hex encoded compact hash code.
        params:
          type: array
          description: A list of parameters to be forwared to the function
        dependencies:
          type: array
          description: A list of python package dependencies required by the implementation
    Dataset:
      title: Dataset
      type: object
      description: A dataset used for near-duplicate benchmarking
      required:
      - name
      - url
      - mode
      properties:
        name:
          type: string
          description: The name of the dataset
        label:
          type: string
          description: Short label used in tables and as folder name
        url:
          type: string
          format: uri
          description: Download url for dataset
        mode:
          type: string
          description: Perceptual mode of media assets
          enum:
          - text
          - image
          - audio
          - video
        installer:
          type: string
          description: Full path to python function that installs the dataset
        samples:
          type: integer
          description: Number of samples to install from the dataset
        clusters:
          type: integer
          description: Number of similarity clusters to build for dataset
        seed:
          type: integer
          description: Seed for reproducible random selection of samples
        download_hash:
          type: string
          description: Hash of unprocessed download data
        data_hash:
          type: string
          description: Hash of processed data folder
    Transformation:
      title: Transformation
      type: object
      description: A transformation being applied to a media asset
      required:
      - name
      - mode
      - function
      properties:
        name:
          type: string
          description: The name of the transformation
        mode:
          type: string
          description: Perceptual mode of media assets
          enum:
          - text
          - image
          - audio
          - video
        function:
          type: string
          description: Full path to python function that applies the transformation
        params:
          type: array
          description: A list of transformation parameters to be used with the function
    Configuration:
      title: Configuration
      type: object
      description: Benchmark configuration
      required:
      - twinspect
      - datasets
      - transformations
      properties:
        twinspect:
          type: string
          description: Configuration file format version
        algorithms:
          type: array
          items:
            $ref: '#/components/schemas/Algorithm'
          description: List of algorithms to be benchmarked
        datasets:
          type: array
          items:
            $ref: '#/components/schemas/Dataset'
          description: List of Datasets
        transformations:
          type: array
          items:
            $ref: '#/components/schemas/Transformation'
          description: List of Transformations
