twinspect: 0.1.0
datasets:
- name: FMA - A Dataset For Music Analysis
  label: fma
  url: https://os.unil.cloud.switch.ch/fma/fma_full.zip
  mode: audio
  installer: twinspect.datasets.fma:install
  samples: 10
