twinspect: 0.1.0
algorithms:
  - name: Image Dhash
    label: image_dhash
    mode: image
    function: twinspect.algos.clip_pch:image_dhash
    dependencies:
      - dhash==1.4
  - name: Image Phash
    label: image_phash
    mode: image
    function: twinspect.algos.clip_pch:image_phash
    dependencies:
      - imagehash==4.3.1
  - name: Image Phash simple
    label: image_phash_simple
    mode: image
    function: twinspect.algos.clip_pch:image_phash_simple
    dependencies:
      - imagehash==4.3.1
  - name: Image CLIP PCH 32 4
    label: image_clip_pch_32_4
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_32_4
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH 16 4
    label: image_clip_pch_16_4
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_16_4
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH 8 4
    label: image_clip_pch_8_4
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_8_4
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH 8 16
    label: image_clip_pch_8_16
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_8_16
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH 16 16
    label: image_clip_pch_16_16
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_16_16
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH 32 16
    label: image_clip_pch_32_16
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_32_16
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH 64 16
    label: image_clip_pch_64_16
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_64_16
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH 128 16
    label: image_clip_pch_128_16
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_128_16
    dependencies:
      - torch==2.1.0
  - name: Image CLIP PCH binary
    label: image_clip_pch_binary
    mode: image
    function: twinspect.algos.clip_pch:image_clip_pch_binary
    dependencies:
      - torch==2.1.0
  - name: ISCC Text-Code V0 64-Bit
    label: text_code_v0_64
    mode: text
    function: twinspect.algos.iscc:text_code_v0_64
    dependencies:
      - iscc-sdk==0.5.9
  - name: ISCC Image-Code V0 64-Bit
    label: image_code_v0_64
    mode: image
    function: twinspect.algos.iscc:image_code_v0_64
    dependencies:
      - iscc-sdk==0.5.9
  - name: ISCC Audio-Code V0 64-Bit
    label: audio_code_v0_64
    mode: audio
    function: twinspect.algos.iscc:audio_code_v0_64
    dependencies:
      - iscc-sdk==0.5.9
  - name: ISCC Video-Code V0 64-Bit
    label: video_code_v0_64
    mode: video
    function: twinspect.algos.iscc:video_code_v0_64
    dependencies:
      - iscc-sdk==0.5.9
datasets:
  - name: STLIB-2000
    label: stlib_2000
    info: The STLIB-2000 is a real-world dataset of 2000 commercial E-Books where each title has
      an EPUB and PDF version. The data has been generously provided by [StreetLib](https://www.streetlib.com/).
      Because the ISCC-SDK does not support OCR yet, titles with image-only E-Books have been removed
      before benchmarking.
    url: https://www.streetlib.com
    mode: text
    installer: twinspect.datasets.dummy:install
  - name: MIRFLICKR-MFND
    label: mirflickr_mfnd
    info: The MFND benchmark ([Connor et al., 2015](http://dx.doi.org/10.5220/0005359705650571))
      is a subset of the real-world MIRFLICKR dataset ([Huiskes & Lew, 2008](https://doi.org/10.1145/1460096.1460104))
      with [annotations](http://www.mir-flickr-near-duplicates.appspot.com/) for near duplicates
      (IND). The Twinspect benchmark automatically downloads and reproduces the tested dataset.
    url: https://mfnd.similarity.eu/data/truthfiles/polito/IND_clusters.txt
    mode: image
    installer: twinspect.datasets.mfnd:install
  - name: ISCC-FMA-10k
    label: iscc_fma_10k
    info: The ISCC-FMA-10k benchmark is a subset of [Free Music Archive Dataset](https://doi.org/10.48550/arXiv.1612.01840).
      The subset is generated by collecting 5000 random audio files (longer than 60 seconds). Additionaly
      10 synthetic transformations are applied to a random selection 500 of the audio files. The
      Twinspect benchmark automatically downloads and reproduces the tested dataset.
    url: https://os.unil.cloud.switch.ch/fma/fma_full.zip
    mode: audio
    installer: twinspect.datasets.fma:install
    samples: 5000
    clusters: 500
    seed: 0
transformations:
  - name: Trim 1 Second
    label: trim-1s-both
    info: Remove 1 seconds of audio from start and end
    mode: audio
    function: twinspect.transformations.audio:trim
    params:
      - 1
      - both
  - name: Trim 5 Seconds
    label: trim-5s-both
    info: Remove 5 seconds of audio from start and end
    mode: audio
    function: twinspect.transformations.audio:trim
    params:
      - 5
      - both
  - name: Fade 8 Seconds
    label: fade-8s-both
    info: Fade in/out 8 seconds at start and end
    mode: audio
    function: twinspect.transformations.audio:fade
    params:
      - 8
      - both
  - name: Transcode MP3 128kbps
    label: transcode-mp3-128kbps
    info: Transcode audio to 128kbps MP3
    mode: audio
    function: twinspect.transformations.audio:transcode
    params:
      - mp3
      - 128
  - name: Transcode OGG 64kbps
    label: transcode-ogg-64kbps
    info: Transcode audio to 64kbps OGG
    mode: audio
    function: twinspect.transformations.audio:transcode
    params:
      - ogg
      - 64
  - name: Transcode AAC 32kbps
    label: transcode-aac-32kbps
    info: Transcode audio to 32kbps AAC
    mode: audio
    function: twinspect.transformations.audio:transcode
    params:
      - aac
      - 32
  - name: Compress
    label: compress-medium
    info: Apply audio compression (attack 10, release 200, ratio 3, threshold -20)
    mode: audio
    function: twinspect.transformations.audio:compress
    params:
      - medium
  - name: Equalize
    label: equalize
    info: Equalize audio (ffmpeg equalizer=f=1000:t=o:w=200:g=10)
    mode: audio
    function: twinspect.transformations.audio:equalize
  - name: Echo
    label: echo
    info: Apply echo effect (ffmpeg aecho=0.8:0.7:60:0.2)
    mode: audio
    function: twinspect.transformations.audio:echo
  - name: Loudness Normalization
    label: loudnorm
    info: Apply loudness normalization (ffmpeg loudnorm=I=-16:TP=-1.5:LRA=11)
    mode: audio
    function: twinspect.transformations.audio:loudnorm
metrics:
  - name: Execution Speed
    label: speed
    function: twinspect.metrics.speed:speed
  - name: Effectiveness (Precission, Recall, F1-Score)
    label: effectiveness
    function: twinspect.metrics.eff:effectiveness
  - name: Robustness against transformations
    label: robustness
    function: twinspect.metrics.robustness:robustness
  - name: Distribution (All-Pairs Hamming Distances)
    label: distribution
    function: twinspect.metrics.distribution:distribution
benchmarks:
  - algorithm_label: text_code_v0_64
    dataset_label: stlib_2000
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: false
  - algorithm_label: image_code_v0_64
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: audio_code_v0_64
    dataset_label: iscc_fma_10k
    metric_labels:
      - speed
      - effectiveness
      - robustness
      - distribution
    active: false
  - algorithm_label: image_dhash
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_32_4
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_16_4
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_8_4
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_8_16
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_16_16
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_32_16
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_64_16
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_128_16
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_clip_pch_binary
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_phash
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
  - algorithm_label: image_phash_simple
    dataset_label: mirflickr_mfnd
    metric_labels:
      - speed
      - effectiveness
      - distribution
    active: true
