twinspect: 0.1.0
algorithms:
- name: ISCC Audio-Code V0 64-Bit
  label: audio_code_v0
  mode: audio
  function: twinspect.algorithms.iscc:audio_code
  params:
  - 64
  dependencies:
  - iscc-sdk==0.5.5
datasets:
- name: FMA 100/10 Synth
  label: fma_100
  url: https://os.unil.cloud.switch.ch/fma/fma_full.zip
  mode: audio
  installer: twinspect.datasets.fma:install
  samples: 100
  clusters: 10
  seed: 0
transformations:
- name: Trim 1 Second
  mode: audio
  function: twinspect.transformations.audio:trim
  params:
  - 1
  - both
- name: Trim 5 Seconds
  mode: audio
  function: twinspect.transformations.audio:trim
  params:
  - 5
  - both
- name: Fade 8 Seconds
  mode: audio
  function: twinspect.transformations.audio:fade
  params:
  - 8
  - both
- name: Transcode MP3 128kbps
  mode: audio
  function: twinspect.transformations.audio:transcode
  params:
  - mp3
  - 128
- name: Transcode OGG 64kbps
  mode: audio
  function: twinspect.transformations.audio:transcode
  params:
  - ogg
  - 64
- name: Transcode AAC 18kbps
  mode: audio
  function: twinspect.transformations.audio:transcode
  params:
  - aac
  - 18
- name: Compress
  mode: audio
  function: twinspect.transformations.audio:compress
  params:
  - medium
- name: Equalize
  mode: audio
  function: twinspect.transformations.audio:equalize
- name: Echo
  mode: audio
  function: twinspect.transformations.audio:echo
- name: Loudness Normalization
  mode: audio
  function: twinspect.transformations.audio:loudnorm
