twinspect: 0.1.0
algorithms:
- name: ISCC Audio-Code V0 64-Bit
  label: audio_code_v0
  mode: audio
  function: twinspect.algorithms.iscc:audio_code
  params:
  - 64
  dependencies:
  - iscc-sdk==0.5.5
datasets:
- name: FMA 10/3 Synth
  label: fma_10
  url: https://os.unil.cloud.switch.ch/fma/fma_full.zip
  mode: audio
  installer: twinspect.datasets.fma:install
  samples: 10
  clusters: 3
  seed: 0
  download_hash: 0804eacde5a4791e
  data_hash: 19b60596942ac04c
transformations:
- name: Trim 0.1 Seconds
  mode: audio
  function: twinspect.transformations.audio:trim
  params:
  - 0.1
  - both
- name: Trim 1 Second
  mode: audio
  function: twinspect.transformations.audio:trim
  params:
  - 1
  - both
- name: Trim 5 Seconds
  mode: audio
  function: twinspect.transformations.audio:trim
  params:
  - 5
  - both
- name: Fade 8 Seconds
  mode: audio
  function: twinspect.transformations.audio:fade
  params:
  - 8
  - both
- name: Transcode MP3 128kbps
  mode: audio
  function: twinspect.transformations.audio:transcode
  params:
  - mp3
  - 128
- name: Transcode OGG 64kbps
  mode: audio
  function: twinspect.transformations.audio:transcode
  params:
  - ogg
  - 64
- name: Transcode AAC+v2 18kbps
  mode: audio
  function: twinspect.transformations.audio:transcode
  params:
  - aac
  - 18
- name: Mastering Low
  mode: audio
  function: twinspect.transformations.audio:master
  params:
  - low
- name: Mastering Medium
  mode: audio
  function: twinspect.transformations.audio:master
  params:
  - medium
- name: Mastering Strong
  mode: audio
  function: twinspect.transformations.audio:master
  params:
  - strong
